---
abstract: "Client for LinkedIn's Kafka"
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kafka-Client
requires:
  Digest::CRC: 0
  IO::Socket: 0
  Moose: 0
resources:
  repository: https://github.com/magazinesdotcom/kafka-client
version: 0.01
